'use client';

import { FadeIn } from '@/components/motion/FadeIn';
import Link from 'next/link';

export default function ReferencePage() {
  return (
    <div className="mx-auto w-full max-w-4xl px-6 py-12 font-mono">
      <FadeIn>
        <div className="mb-12 border-4 border-text p-6 bg-surface shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
          <h1 className="text-4xl font-black text-text mb-2 uppercase tracking-tight">
            EDGAR API Reference
          </h1>
          <p className="text-text-muted">
            Technical specifications for SEC EDGAR machine-to-machine communication.
          </p>
        </div>
      </FadeIn>

      <div className="grid gap-8">
        <FadeIn delay={0.1}>
          <section className="border-4 border-text p-6 bg-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <h2 className="text-2xl font-black text-text mb-4 underline">
              1. Authentication Model
            </h2>
            <div className="space-y-4 text-sm leading-relaxed text-text">
              <p>The EDGAR API uses a dual-token system for authorized actions:</p>
              <ul className="list-disc ml-6 space-y-2">
                <li>
                  <strong className="text-green-600">Filer API Token:</strong> Issued by the EDGAR
                  account/CIK. Authenticates the entity. Must be provided in the request header.
                </li>
                <li>
                  <strong className="text-green-600">User API Token:</strong> Generated by an
                  individual account administrator. Authenticates the person performing the action.
                </li>
              </ul>
              <div className="bg-text text-surface p-3 text-xs mt-4">
                NOTE: Most APIs require both tokens. Submission Status and Operational Status APIs
                may require fewer.
              </div>
            </div>
          </section>
        </FadeIn>

        <FadeIn delay={0.2}>
          <section className="border-4 border-text p-6 bg-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <h2 className="text-2xl font-black text-text mb-4 underline">2. API Endpoints</h2>
            <div className="space-y-6 text-sm leading-relaxed text-text">
              <div>
                <h3 className="font-bold text-green-600 mb-2">Submission API</h3>
                <p>
                  Allows filings to be submitted programmatically. Requires Filer Token + User Token
                  + Submission Data.
                </p>
              </div>
              <div>
                <h3 className="font-bold text-green-600 mb-2">Submission Status API</h3>
                <p>Retrieves status of submissions using Filer Token and Accession Number(s).</p>
              </div>
              <div>
                <h3 className="font-bold text-green-600 mb-2">Account Information API</h3>
                <p>
                  Returns CIK details (company name, address, CCC) using Filer Token + User Token.
                </p>
              </div>
            </div>
          </section>
        </FadeIn>

        <FadeIn delay={0.3}>
          <section className="border-4 border-text p-6 bg-surface shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <h2 className="text-2xl font-black text-text mb-4 underline">
              3. Request Requirements
            </h2>
            <div className="space-y-4 text-sm leading-relaxed text-text">
              <p>
                All requests must include a descriptive{' '}
                <code className="bg-text/10 px-1">User-Agent</code> header.
              </p>
              <div className="bg-text/5 border-2 border-text p-3 text-xs font-mono italic">
                Example: "Company Name (contact@company.com)"
              </div>
              <p>
                Failure to provide a valid User-Agent will result in the request being blocked by
                SEC servers.
              </p>
            </div>
          </section>
        </FadeIn>
      </div>

      <div className="mt-12 text-center">
        <Link href="/" className="text-sm font-bold text-green-600 hover:underline">
          ← RETURN TO DASHBOARD
        </Link>
      </div>
    </div>
  );
}
